baseURL = "https://adamofsound.github.io/gaming-hub/"
languageCode = "en-us"
title = "GameHub Daily"
theme = "PaperMod"
publishDir = "docs"

[params]
  author = "Vendel Ottenberg"
  description = "PC, Xbox, PlayStation & Mobile gaming news, reviews & media"
  showReadingTime = false
  disableAssetFingerprinting = false
  ShowReadingTime = false
  ShowShareButtons = false
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
[params.assets]
  customJS = ["js/ads.js"]